[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ptmelt"
version = "0.1.4"
description = "PyTorch Machine Learning Toolbox (PT-MELT)"
readme = "README.md"
license = { text = "BSD 3-Clause License" }
authors = [
    { name = "Nicholas T. Wimer", email = "nwimer@nrel.gov" },
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Science/Research",
]
dependencies = [
    "pytest",
    "torchinfo",
    "tqdm",
    "scikit-learn",
    "matplotlib",
    "ray[data,train,tune,serve]",
    "hyperopt",
    "optuna",
    "hpbandster",
    "ConfigSpace",
    "bayesian-optimization",
    "ax-platform",
    "safetensors",
    'torch ; sys_platform == "linux" or sys_platform == "darwin"',
    'torchvision ; sys_platform == "linux" or sys_platform == "darwin"',
    'torchaudio ; sys_platform == "linux" or sys_platform == "darwin"',
]

[project.urls]
Homepage = "https://github.com/NREL/pt-melt"

[tool.setuptools.packages.find]
include = ["ptmelt*"]
