[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ptmelt"
version = "0.1.4"
description = "PyTorch Machine Learning Toolbox (PT-MELT)"
readme = "README.md"
requires-python = ">=3.11"
license = "BSD-3-Clause"
authors = [
    { name = "Nicholas T. Wimer", email = "nwimer@nrel.gov" },
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Science/Research",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "pytest",
    "torchinfo",
    "tqdm",
    "scikit-learn",
    "matplotlib",
    "ray[data,train,tune,serve]",
    "hyperopt",
    "optuna",
    "hpbandster",
    "ConfigSpace",
    "bayesian-optimization",
    "ax-platform",
    "safetensors",
    "torch",
    "torchvision",
    "torchaudio",
]

[project.urls]
Homepage = "https://github.com/NREL/pt-melt"

[project.optional-dependencies]
dev = [
    "ruff",
    "ipython",
]
test = [
    "pytest",
    "pytest-cov",
]
doc = [
    "sphinx",
    "myst-parser",
    "pydata-sphinx-theme",
]

[tool.setuptools.packages.find]
include = ["ptmelt*"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64"]

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev", "doc", "test"], solve-group = "default" }
doc = { features = ["doc"], solve-group = "default" }
test = { features = ["test"], solve-group = "default" }

[tool.pixi.pypi-dependencies]
ptmelt = { path = ".", editable = true }

[tool.pixi.feature.dev.tasks]
lint = "ruff check ./ptmelt"
format = "ruff format ./ptmelt"

[tool.pixi.feature.test.tasks]
tests = "pytest -vv ptmelt/"

[tool.pixi.feature.doc.tasks]
docs = { cmd = "make html", cwd = "Docs" }
